version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/myapp

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis  
    ports:
      - "6379:6379"